/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package io.vtown.WeiTangApp.comment.contant;

import android.util.Log;

public class LogUtils {
    
    public static void i( String content) {
        if(Constants.Debug) {
           System.out.println(content);
        }
    }
}
